config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  # Welcome
  get "/"                  => 'welcome#index', as: 'root'
  get '/search'            => 'restaurants#search'
  post '/favorite'         => 'restaurants#add_favorite'
  post '/unfavorite'       => 'restaurants#remove_favorite'

  resources :users, except: [:index]
  resources :restaurants, only: [:index, :show]
  resources :reviews, except: [:show, :index]
  resources :favorites, except: [:show, :index, :destroy]

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    
    #only logged in users can create reviews 
    can :create, Review

    #current user can only update reviews that belong to them
    can :update, Review do |review|
        user == review.user
    end

    #current user can only destroy reviews that belong to them 
    can :destroy, Review do |review|
        user == review.user
    end
    
  end 
end

app/models/factual.rb
module Factual
  FACTUAL_KEY = ENV["FACTUAL_API_KEY"]


  # Get info from Factual
  def self.restaurant_info(zip)
    url = URI.escape("http://api.v3.factual.com/t/restaurants-us?filters={\"price\":\"1\",\"postcode\":\"#{zip}\"}&KEY=#{FACTUAL_KEY}&limit=1")
    response = HTTParty.get(url)['response']['data']
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :reviews
  validates_presence_of :zip_code, :name, :latitude, :longitude, :address
  scope :where_zip, -> (term) { where("restaurants.zip_code = ?", term)}

  #gets all of restaurant instance's reviews and averages rating 
  def average_worth_it()
    self.reviews.average(:worth_it).round
  end

  #returns string for particular rating
  def worth_it_rating(rating)
    rating_hash = { 
      5 => "Totally Torth It!",
      4 => "Pretty Worth It",
      3 => "Kinda Worth It",
      2 => "Not Worth It", 
      1 => "Meh!" }

    return rating_hash[rating]
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant
  validates_presence_of :comment, :worth_it, :user_id, :restaurant_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable

  has_many :reviews, dependent: :destroy
  has_and_belongs_to_many :restaurants
  validates_presence_of :first_name, :last_name, :username, :email, :encrypted_password
  validates_uniqueness_of :username, :email

  #creates join table relationship btw user and restaurant
  def favorite(restaurant)
    unless self.restaurants.include?(restaurant)
      self.restaurants.push(restaurant)
    end
  end

  #destroys join table relationship btw user and restaurant
  def unfavorite(restaurant)
    if self.restaurants.include?(restaurant)
      self.restaurants.destroy(restaurant)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:sign_up) << :first_name
    devise_parameter_sanitizer.for(:sign_up) << :last_name
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def search
    zip = params[:search]
    @restaurants = Restaurant.where_zip(zip).to_json.html_safe
  end

  def add_favorite
    @restaurant = Restaurant.find(params[:id])
    current_user.favorite(@restaurant)
  end

  def remove_favorite
    @restaurant = Restaurant.find(params[:id])
    current_user.unfavorite(@restaurant)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
    authorize! :create, @review
  end

  def create
    @review = Review.new
    authorize! :create, @review
    @review.worth_it = params[:worth_it]
    @review.comment = params[:comment]
    @review.user_id = current_user.id
    @review.restaurant_id = params[:restaurant_id]
    @review.update(review_params)
    @review.save
  end

  def edit
    @review = Review.find(params[:id])
    @restaurant = @review.restaurant
    authorize! :update, @review
  end

  def update
    @review = Review.find(params[:id])
    authorize! :update, @review
    @review.update(review_params)
  end

  def destroy
    @review = Review.find(params[:id])
    authorize! :destroy, @review
    @review.destroy
  end

  private
  def review_params
    params.require(:review).permit(:user_id, :restaurant_id, :worth_it, :comment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, only: [:edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:current_user] = @user.id
      redirect_to(root_path)
    else
      render(:new)
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to(user_path(@user))
    else
      render(:edit)
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:current_user] = nil
    redirect_to(root_path)
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :encrypted_password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>froogalr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <script type="text/javascript" src="//use.typekit.net/mux2lap.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
</head>
<body>
<header id="main-header">
  <div id="header-block">
    <h1><%= link_to('froogalr', root_path) %></h1>
    <div id="header-content">
      <% if user_signed_in? %>
        Welcome back, <%= current_user.first_name %>! |
        <%= link_to('Restaurants', restaurants_path) %> |
        <%= link_to('My Profile', user_path(current_user)) %> |
        <%= link_to('Sign out', destroy_user_session_path, method: :delete)%>
      <% else %>
        <%= link_to('Restaurants', restaurants_path) %> |
        <%= link_to('Sign in', new_user_session_path) %> |
        <%= link_to('Sign up', new_user_registration_path) %> |
      <% end %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
  </div>
</header>
<div id="main-content">
  <%= yield %>
</div>
</body>
</html>

app/views/restaurants/add_favorite.js.erb
//chances favorite button to unfavorite on action
var form = $('#favorite').closest('form');
form.attr('action','/unfavorite');
$('[type="submit"]#favorite').val('Unfavorite');

app/views/restaurants/index.html.erb
<!-- Zipcode search form -->
<%= form_tag('/search', remote: true, method: :get, id: 'map-search') do %>
  <p><%= text_field_tag :search,nil, placeholder: 'Zip Code (10001)' %><p>
  <p><%= submit_tag 'Search By Zip Code' %></p>
<% end %>

<% google_maps_key = ENV["GOOGLE_MAPS_KEY"] %>
<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=<%= google_maps_key %>&callback=initialize">
</script>

<script type="text/javascript">
  window.onload = loadScript;
</script>

<div id="map-canvas" class="index-map"></div>
<div id="map-modal">
  <span id="close">Close</span>
  <div id="modal-content">
    <div id="restaurant-information">
    </div>
  </div>
</div>

app/views/restaurants/remove_favorite.js.erb
//chances remove favorite button to favorite on action
var form = $('#favorite').closest('form');
form.attr('action','/favorite');
$('[type="submit"]#favorite').val('Favorite');

app/views/restaurants/search.js.erb
$(function() {
  $('body').on('click', '#map-modal', hideModal);
});

function mapIt(){
  var restaurants = <%= @restaurants %>;

  for (var i = 0; i < restaurants.length; i++) {
    var myLatlng = new google.maps.LatLng(restaurants[i].latitude,restaurants[i].longitude);

    var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      title: restaurants[i].name,
      address: restaurants[i].address,
      id: restaurants[i].id,
      zip: restaurants[i].zip_code,
      telephone: restaurants[i].telephone,
      website: restaurants[i].website,
      cuisine: restaurants[i].cuisine,
    });

    google.maps.event.addListener(marker, 'click', function() {
      var reviews = <%= @reviews %>
      console.log(this);
      var modal = $('#map-modal');
      var modalContent = $('#modal-content');
      modalContent.empty();;
      var restaurantInfo = $('<div id="restaurant-information">' + '<h3>'+ this.title +'</h3>'
                           + '<p>'+ this.address + ' ' + this.zip +'</p>'
                           + '<p>'+ this.telephone +'</p>'
                           + (this.website === null ? '' : ('<p><a href="'+ this.website +'" target="_blank">'+ this.website +'</a></p>'))
                           + '<a href="/restaurants/' + this.id + '">More Info</a>'+ '</div>');
      modalContent.append(restaurantInfo);
      modal.show();
    });
  };
}

function hideModal() {
  $('#map-modal').find('div').empty();
  $("#map-modal").hide();
}

mapIt();

app/views/restaurants/show.html.erb
<% google_maps_key = ENV["GOOGLE_MAPS_KEY"] %>
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />

<script type="text/javascript"
  src="https://maps.googleapis.com/maps/api/js?key=<%= google_maps_key %>">
</script>

<script type="text/javascript">
  function initialize() {
    var myLatlng = new google.maps.LatLng(<%= @restaurant.latitude %>,<%= @restaurant.longitude %>);
    var mapOptions = {
      zoom: 16,
      center: myLatlng
    }
  var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
  var marker = new google.maps.Marker({
      position: myLatlng,
      map: map,
      title: '<%= @restaurant.name %>'
  });
}
  google.maps.event.addDomListener(window, 'load', initialize);
</script>

<div id="restaurants-show-content">
  <!-- Shows favorite button if signed in -->
  <% if current_user %>
    <% if current_user.restaurants.include?(@restaurant) %>
      <%= button_to 'Unfavorite', '/unfavorite', remote: true, method: :post, params: {id: @restaurant.id}, id: 'favorite' %>
    <% else %>
      <%= button_to 'Favorite', '/favorite', remote: true, method: :post, params: {id: @restaurant.id}, id: 'favorite' %>
    <% end %>
  <% end %>

  <!-- Restaurant Information -->
  <h2>Name: <%= @restaurant.name %></h2>
  <p> Address: <%= @restaurant.address %> <%= @restaurant.zip_code %></p>
  <p>Phone Number: <%= @restaurant.telephone %></p>
  <p><a href="<%= @restaurant.website %>" target="_blank"><%= @restaurant.website %></a></p>
  <p>Cuisine: <%= @restaurant.cuisine %></p>
  <p>Time: <%= @restaurant.hours %></p>

  <% if @restaurant.reviews.count > 1 %>
    <p class="worth-<%= @restaurant.reviews.average(:worth_it).round %> rating">
      <span class="rating-number"><%= rating = @restaurant.reviews.average(:worth_it).round %></span><br>
      <%= @restaurant.worth_it_rating(rating) %>
    </p>
  <% end %>

  <div id="map-canvas" class="restaurant-show-map"></div>

  <div id="reviews_container">
    <div class="hidden-div" id="<%= @restaurant.id %>"></div>
      
      <% if user_signed_in? %>
        <%= render 'reviews/form' %>
      <% end %>
   
    <% @restaurant.reviews.each do |review| %>
    <div class="review" id="<%= dom_id(review) %>">
      <%= render review %>
    </div>
    <% end %>
    
  </div>
</div>

app/views/reviews/_form.html.erb
<%= form_for @review, remote: true do |f| %>
  <div id="worth-it-rating">
    Was it worth it?<br>
    1 <%= f.radio_button :worth_it, '1', :checked => 1 %>
    2 <%= f.radio_button :worth_it, '2', :checked => 2 %>
    3 <%= f.radio_button :worth_it, '3', :checked => 3 %>
    4 <%= f.radio_button :worth_it, '4', :checked => 4 %>
    5 <%= f.radio_button :worth_it, '5', :checked => 5 %>
  </div>

  <div id="add-comment-box">
    <%= f.text_area :comment %>
  </div>

  <%= f.hidden_field(:restaurant_id, value: @restaurant.id) %>
  <%= f.submit('Post Review') %>
<% end %>

app/views/reviews/_review.html.erb
<h3 class="username"><%= link_to(review.user.username, user_path(review.user.id)) %></h3>
<div class="worth-it">Worth it? <%= review.worth_it %></div>
<div class="review-comment"><%= review.comment %></div>

<!-- authorized users can see links to update and destroy -->
<% if can?(:update, review) %>
  <%= link_to('Edit', edit_review_path(review), remote: true) %> |
<% end %>
<% if can? :destroy, review %>
  <%= link_to 'Delete', review, remote: true, method: :delete, data: {confirm: 'Are you sure you want to delete this review?'} %>
<% end %>

app/views/reviews/create.js.erb
//renders HTML for created review, grabs reviews container and makes new review DIV
var reviewHtml = '<%= j(render @review) %>';
var reviewsContainer = $('#reviews_container');
var domId = '<%= dom_id(@review) %>'
var reviewDiv = $('<div class="review" id="' + domId +'"></div>')

//adds rendered review HTML to review div and appends that to container on page
reviewDiv.html(reviewHtml);
reviewDiv.appendTo(reviewsContainer);

//removes create form from page
$('#new_review').remove()

app/views/reviews/destroy.js.erb
//gets the review by id and removes from page
var id = <%= @review.id %>
var review = $('#review_' + id);
review.remove();

app/views/reviews/edit.js.erb
//removes review to edit from page
$('#new_review').remove()

//renders review form html, gets current review to edit, replaces html with new review
var reviewHtml = '<%= j(render 'reviews/form') %>';
var domId = '<%= dom_id(@review) %>';
var reviewToEdit = $('#' + domId);
reviewToEdit.html(reviewHtml);

app/views/reviews/update.js.erb
//gets new review HTML and element of old review to update
var newReview = '<%= j(render @review) %>';
var domId = '<%= dom_id(@review) %>';
var oldReview = $('#' + domId);

//takes old review div and replaces with new review HTML
var reviewToAdd = $(newReview);
oldReview.replaceWith(reviewToAdd);

app/views/users/show.html.erb
<div id="user-show-content">
  <div id="top-content">
    <%= link_to('Edit Account', edit_user_registration_path, :id => 'edit-user') %>
    <h2 class="username"><%= @user.username %></h2>
    <h3>Name: <%= "#{@user.first_name} #{@user.last_name}" %></h3>
  </div>
  <div id="user-favorites">
    <ul class="favorites-list">
      <h3 id="favorites-header">Favorites</h3>
      <% if @user.restaurants.count < 1 %>
        <li>This user has no favorites</li>
      <% else %>
        <% @user.restaurants.each do |restaurant| %>
          <li class= "favorite-restaurant"><%= link_to(restaurant.name, restaurant_path(restaurant)) %></li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div id="user-reviews">
    <div class="reviews">
      <h3 id="reviews-header">Reviews</h3>
        <% @user.reviews.each do |review| %>
          <div class="review-content">
            Comment: <p class="comment"><%= review.comment %></p><br>
            <p class="worth-it">Was it worth it? <%= review.worth_it %></p><br>
            <a href="/restaurants/<%= review.restaurant_id %>">Click to view the restaurant's page</a>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<script type="text/javascript">
  $.backstretch("https://dl.dropboxusercontent.com/u/54485160/project-2/froogalr-bg.jpg");
</script>
<div id="home-content">
  <h1>Find cheap eats in New York City for under $15</h1>
  <%= link_to('Look For Restaurants', restaurants_path, class: 'home-button') %>
</div>